package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTrainer;
import org.linlinjava.litemall.db.domain.LitemallTrainerExample;

public interface LitemallTrainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    long countByExample(LitemallTrainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTrainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int insert(LitemallTrainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTrainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    LitemallTrainer selectOneByExample(LitemallTrainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    LitemallTrainer selectOneByExampleSelective(@Param("example") LitemallTrainerExample example, @Param("selective") LitemallTrainer.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    List<LitemallTrainer> selectByExampleSelective(@Param("example") LitemallTrainerExample example, @Param("selective") LitemallTrainer.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    List<LitemallTrainer> selectByExample(LitemallTrainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    LitemallTrainer selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTrainer.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    LitemallTrainer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    LitemallTrainer selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTrainer record, @Param("example") LitemallTrainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTrainer record, @Param("example") LitemallTrainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTrainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTrainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTrainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_trainer
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}