package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAppointment;
import org.linlinjava.litemall.db.domain.LitemallAppointmentExample;

public interface LitemallAppointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    long countByExample(LitemallAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int insert(LitemallAppointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAppointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    LitemallAppointment selectOneByExample(LitemallAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    LitemallAppointment selectOneByExampleSelective(@Param("example") LitemallAppointmentExample example, @Param("selective") LitemallAppointment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    List<LitemallAppointment> selectByExampleSelective(@Param("example") LitemallAppointmentExample example, @Param("selective") LitemallAppointment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    List<LitemallAppointment> selectByExample(LitemallAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    LitemallAppointment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAppointment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    LitemallAppointment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    LitemallAppointment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAppointment record, @Param("example") LitemallAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAppointment record, @Param("example") LitemallAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAppointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAppointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_appointment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}